name: ai_barcode web deploy

on:
  push:
    branches:
      - master

jobs:
  web_build_and_deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
      - name: "Web Build 🔧"
        run: |
          flutter pub get
          flutter run -d chrome --web-renderer html
      - name: "Web Deploy 🚀"
          # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: '${{ secrets.commit_secret }}'
          branch: gh-pages
          folder: build/web
